# @package _global_
experiment_info:
  project_name: "transformers-for-rl"
  experiment_name: ${memory.name}_${env.name}
  device: "cpu"
  seed: 10
  total_episodes: 10000
  eval_agent: True
  eval_episodes: 10000

# Logging and Graphing
logging:
  use_comet: False
  log_interval: 100
  plot_viz: False
  plot_frequency: 100

# Environment Info
env:
  name: "memory_len"
  max_steps_per_episode: 1000
  window: 1
  device: ${experiment_info.device}

# Save directory for logs, data, and graphs
hydra:
  run:
    dir: results/${env.window}/${memory.name}/

defaults:
  - agent: a2c
  - memory: act_gtrxl
