# @package _global_
memory_models: ["GTrXL", "TransformerXL", "ReZeroXL"]
envs: ["memory_len/0"]
seed: 1
plot_bsuite: False
plot_training: False
plot_eval: False
plot_attn_weights: True
plot_frequency: 100

# Default directory
hydra:
  run:
    dir: results/